apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 430186030227.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 430186030227.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: 0ef720e5
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
